name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.2'
    - name: Build
      run: swift build
    - name: Tests
      run: swift test